[Icon Theme]
Name=MW-Yaru-Blue
Comment=An icon theme for Linux desktops by mrweb
Inherits=MW-Yaru-Blue,Yaru,MW-Base-Yaru,Humanity,hicolor
Example=x-directory-normal

# Directory list
Directories=mw/mw,mw/mimetypes,mw/apps

[mw/mw]
Context=MW
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[mw/mimetypes]
Context=Mimetypes
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[mw/apps]
Context=Apps
Size=16
MinSize=16
MaxSize=256
Type=Scalable
